### ISSUE TITLE
logo image in the navbar is not linked correctly

### ISSUE THREAD

**Issue by BinukaDs** [Dog-Face-Development/dog-face-development.github.io#41]
Screenshot: 
![image](https://user-images.githubusercontent.com/77571607/194744135-9b6cca9f-79ae-41cc-953b-33351bce826e.png)

I would like to fix this issue, please assign me :)

**Comment by willtheorangeguy** [comment]
It has been assigned.

**Comment by willtheorangeguy** [comment]
Fixed by #42.
