### ISSUE TITLE
how do I sign the CLA?

### ISSUE THREAD

**Issue by BinukaDs** [Dog-Face-Development/dog-face-development.github.io#43]

**Comment by willtheorangeguy** [comment]
On the pull request copy and paste this text: I have read the CLA Document, and I hereby sign the CLA.

**Comment by BinukaDs** [comment]
as the pull request name?

**Comment by willtheorangeguy** [comment]
No, copy and paste it as a comment.

**Comment by BinukaDs** [comment]
then, unlock the conversation please :)

**Comment by willtheorangeguy** [comment]
Sorry, I did not realize that, it has been unlocked.

**Comment by willtheorangeguy** [comment]
Merged!

**Comment by BinukaDs** [comment]
isn't this a hacktoberfest repo?

**Comment by willtheorangeguy** [comment]
It is, I have added the `hacktoberfest-accepted` label.
