### ISSUE TITLE
Mobile responsiveness issues - navbar and project sections

### ISSUE THREAD

**Issue by HassanShanJava** [Dog-Face-Development/dog-face-development.github.io#45]
Hi,
I see there is no navbar with the website on mobile mode when I click the hamburger menu, I would like to build that. Also, I would like to make some changes to the project section in the mobile view again, and see if I can make the user experience better overall.

issues:
![image](https://user-images.githubusercontent.com/55858014/194853685-f988a865-c9c8-4d18-a449-165de99c224d.png)

![image](https://user-images.githubusercontent.com/55858014/194853786-98c05547-5dba-4dda-8a0f-8cb642a349aa.png)

**Comment by willtheorangeguy** [comment]
@HassanShanJava sounds good! Just open a PR for what you want to fix.

Thanks

**Comment by willtheorangeguy** [comment]
You can reopen if you are going to continue development.
