### ISSUE TITLE
Feature: Enhance README.md

### ISSUE THREAD

**Issue by utkarsh006** [Dog-Face-Development/dog-face-development.github.io#50]
- Enhance README.md of your repository.
- Create a separate file for contributing guidelines.
- Improve the UI of README.
- Assign me the issue under hacktoberfest.

**Comment by willtheorangeguy** [comment]
Hi, currently the project has a separate file for contribution guidelines, but you are more than welcome to look at the README. Please make sure it stays in conistent form with the other [Dog Face Development projects on GitHub](https://github.com/Dog-Face-Development).
